apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-admin
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z admin-server.petclinic 9090; do echo waiting for admin; sleep 5; done']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: petclinic
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-admin
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z admin-server.petclinic 9090; do echo waiting for admin; sleep 5; done']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: petclinic
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-admin
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z admin-server.petclinic 9090; do echo waiting for admin; sleep 5; done']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-admin
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z admin-server.petclinic 9090; do echo waiting for admin; sleep 5; done']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-admin
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z admin-server.petclinic 9090; do echo waiting for admin; sleep 5; done']
