apiVersion: v1
kind: Service
metadata:
  name: visits-service
  labels:
    app: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
