apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  labels:
    app: genai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: tienphatng237/petclinic-genai-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: OPENAI_API_KEY
            - name: AZURE_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_KEY
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_ENDPOINT

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
